config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 8 routes total
  # get 'users', to: 'users#index'
  # get 'users/:id', to: 'users#show', as: 'user'
  # post 'users', to: 'users#create'
  # patch 'users/:id', to: 'users#upate'
  # put 'users/:id', to: 'users#update'
  # delete 'users/:id', to: 'users#destroy'
  # get 'users/new', to: 'users#new', as: 'new_user'
  # get 'users/:id/edit', to: 'users#edit', as: 'edit_user'
  
  resources :users do
    resources :pets, only: [:index, :new]
  end

  resources :pets, only: [:create, :show, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
# == Schema Information
#
# Table name: pets
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  ttype      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
class Pet < ApplicationRecord
    TYPE = ["dog", "cat", "hamster"]

    validates :name, :user_id, :ttype, presence: true
    validates :ttype, inclusion: TYPE

    belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id          :bigint           not null, primary key
#  category    :string
#  description :text
#  email       :string           not null
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class User < ApplicationRecord
    validates :name, :email, presence: true
   
    # def year_not_in_future
    #     errors[:year] << "cannot be in the future" unless year > 2016
    # end

    has_many :pets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
    def index
        @pets = Pet.all
        render :index
    end

    def show
        @pet = Pet.find(params[:id])

        render :show
    end

    def new
        @user = User.find(params[:user_id])
        @pet = Pet.new

        render :new
    end

    def create
        @pet = Pet.new(pet_params)
        @user = @pet.user

        if @pet.save
            redirect_to user_url(@user)
        else
            render :new
        end
    end

    def destroy
        @pet = Pet.find(params[:id])
        @user = @pet.user

        if @pet.destroy
            redirect_to user_pets_url(@user)
        else
            render plain: "cannot destroy, pet too precious"
        end
    end

    private

    def pet_params
        params.require(:pet).permit(:name, :ttype, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all 
        # render json: user
        render :index
    end

    def show
        @user = User.find_by(id: params[:id])

        # render :show
        if @user
            render :show
        else
            # render :index, below is using the prefix, or can use '/users' 
            redirect_to users_url
        end
    end

    def new
        @user = User.new

        render :new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            #show user hero show page
            # cat_url(@cat) == /cats/(id)
            redirect_to user_url(@user)
        else
            #show user the new user form
            render :new
            # render @user.errors.full_messages, status: :unprocessable_entity
        end
    end

    # 1. GET /cats/new to fetch a form
    # 2. user fills out the form, click submit
    # 3. POST /cats the data in the form
    # 4. Create actions is invoked, cat is created.
    # 5. Send client a redirect to /cats/#{id}
    # 6. Client makes a GET request for /cats/#{id}
    # 7. show action for newly created cat is invoked

    def update
        user = User.find_by(id: params[:id])

        if user.update(user_params)
            render json: user
        else
            render json: user.errors.full_messages, status: :unprocessable_entity
        end
    end

    def destroy
        user = User.find_by(id: params[:id])

        if user.destroy
            redirect_to users_url
        else
            render json: "Cannot destroy user, too important"
        end

        # 1. GET /cats
        # 2. Click delete button
        # 3. Sends POST /cats/123; but _method="delete" so rails understands
        #      to do a destroy
        # 4. Destroys the cat. Issues a redirect to the client
        # 5. Client gets /cats again

    end 

    private

    def user_params
        params.require(:user).permit(:name, :email, :category, :description)
    end     


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Usersapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/index.html.erb
<h1>All the pets!</h1>

<%# ruby code that will not be printed%>
<%#= ruby code that we want to render%> 


<ul>
    <% @pets.each do |pet| %>
        <li>
        <a href="<%= pet_url(pet) %>"> <%= pet.name %></a>
        
        <%# want to add delete button, but forms can only make get/post %>
        <form action="<%= pet_url(pet) %>" method="post">
            <input type="hidden" name="_method" value="delete">
            <input type="submit" value="delete pet">
       
        </form>
        </li>
    <% end %>
</ul>

 <a href="<%= new_user_pet_url %>">New Pet</a>

app/views/pets/new.html.erb
<h1><%= @user.name %>'s New Pet</h1>

<%# action: url to which we want to send data  %>
<%# method: http method that we want to use  %>

<%# action= also accepts users_url  %>
<form action="/pets" method="post">
    <input type="hidden" name=pet[user_id] value="<%= @user.id %>">

    <label for="pet_name">Name</label>
    <input id="pet_name" 
            type="text" 
            name="pet[name]"
            value="<%= @pet.name %>">

    <br>

    <label for="pet_type">Type</label>
    <select name="pet[ttype]" id="pet_ttype">
    <% Pet::TYPE.each do |type|%>
        <option value=<%= type %> <%= "selected" if @pet.ttype == type %>>
        <%= type.upcase%>
        </option>
    <% end %>    
    </select>

    <input type="submit" value="Create Pet">
</form>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<pre><%= @pet.to_json %></pre>

<a href="<%= pets_url %>">Index Page</a>

app/views/users/index.html.erb
<h1>All the users!</h1>

<%# ruby code that will not be printed%>
<%#= ruby code that we want to render%> 


<ul>
    <% @users.each do |user| %>
        <li>
        <a href="<%= user_url(user) %>"> <%= user.name %></a>
        
        <%# want to add delete button, but forms can only make get/post %>
        <form action="<%= user_url(user) %>" method="post">
            <input type="hidden" name="_method" value="delete">
            <input type="submit" value="delete cat">
       
        </form>
        </li>
    <% end %>
</ul>

 <a href="<%= new_user_url %>">New User</a>

app/views/users/new.html.erb
<h1>Add User to our database!!</h1>

<%# action: url to which we want to send data  %>
<%# method: http method that we want to use  %>

<%# action= also accepts users_url  %>
<form action="/users" method="post">
    <label for="user_name">Name</label>
    <input id="user_name" 
            type="text" 
            name="user[name]"
            value="<%= @user.name %>">

    <br>

    <label for="user_email">Email</label>
    <input id="user_email" 
            type="text" 
            name="user[email]"
            value="<%= @user.email %>">

    <br>

    <input type="submit" value="Add User">
</form>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<pre><%= @user.to_json %></pre>

<h2>Email: <%= @user.email %></h2>
<h2>Category: <%= @user.category %></h2>

<h3>Description</h3>
<p><%= @user.description%> </p>

<a href="<%= new_user_pet_url(@user) %>">New Pet</a>

<a href="<%= users_url %>">Index Page</a>